<a href="https://colab.research.google.com/github/GannojuRaviShankar/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Explain the difference between descriptive statistics and inferential statistics.

2. Explain Measures of central tendency with examples.

3. Generate five NumPy arrays of different dimensions.

4. Determine the datatype, shape, size, and dimensions of above arrays.

5. Generate two arrays with random float elements in it.

perform all python operations (* + - / % //).
 Also apply all mathematical functions on the two arrays
6.  Create a random NumPy array. Generate mean, mode, median, variance and standard deviation of that array.

7. Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays



## question-1
1.Descriptive Statistics: Descriptive statistics involves methods for summarizing and describing the features of a dataset. It focuses on organizing, summarizing, and presenting data in a meaningful way, often through measures of central tendency (e.g., mean, median, mode), measures of dispersion (e.g., range, variance, standard deviation), and graphical representations (e.g., histograms, box plots, bar charts). Descriptive statistics aim to provide insights into the characteristics of the data, such as its distribution, central tendency, and variability. These statistics are typically used to describe and understand a dataset without making any generalizations beyond the specific data being analyzed.

Inferential Statistics: Inferential statistics involves methods for making predictions, inferences, or generalizations about a population based on a sample of data. It extends the findings from a sample to a larger population, allowing researchers to draw conclusions or make predictions about the population parameters. Inferential statistics often involves hypothesis testing, confidence intervals, regression analysis, and other techniques that help researchers make inferences about the population based on the observed sample data. The goal of inferential statistics is to determine whether the observed patterns in the sample data are likely to be representative of the population as a whole or if they are due to random variation.

## question-2
Measures of central tendency are statistical measures that represent the center or average of a data set. They provide a single value that summarizes the data and helps in understanding its characteristics. The three main measures of central tendency are:

Mean: The arithmetic average of a set of values, calculated by adding up all the values and dividing by the total number of values. For example, the mean of [2, 4, 6, 8, 10] is (2+4+6+8+10)/5 = 6.

Median: The middle value in a sorted list of numbers. If the number of values is odd, the median is the middle number. If the number of values is even, the median is the average of the two middle numbers. For example, the median of [3, 6, 7, 8, 8, 10, 13] is 8.

Mode: The value that appears most frequently in a data set. A data set may have one mode (unimodal), more than one mode (multimodal), or no mode (no repeated values). For example, the mode of [2, 3, 4, 4, 6, 6, 6, 9] is 6.



In [34]:
 #question-3
import numpy as np
array1=np.array([1,2,3,4])
print(array1,array1.ndim)
array2=np.array([[1,2,3,4],[5,6,7,8]])
print(array2,array2.ndim)
array3=np.array([[[1,2,3],[4,5,6],[7,8,9],[2,4,6]]])
print(array3,array3.ndim)
array4 = np.zeros((3, 4))
print(array4, array4.ndim)
array5=np.random.randint(1,10,size=(3,4))
print(array5,array5.ndim)

[1 2 3 4] 1
[[1 2 3 4]
 [5 6 7 8]] 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [2 4 6]]] 3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 2
[[2 1 1 5]
 [1 9 6 8]
 [4 8 2 7]] 2


In [35]:
#question-4
arrays=[array1,array2,array3,array4,array5]

for i,arr in enumerate(arrays, start=1):
   print(f"Array {i}:")
   print("Data Type:",arr.dtype)
   print("Shape:", arr.shape)
   print("Size:", arr.size)
   print("Dimensions:", arr.ndim)
   print()

Array 1:
Data Type: int64
Shape: (4,)
Size: 4
Dimensions: 1

Array 2:
Data Type: int64
Shape: (2, 4)
Size: 8
Dimensions: 2

Array 3:
Data Type: int64
Shape: (1, 4, 3)
Size: 12
Dimensions: 3

Array 4:
Data Type: float64
Shape: (3, 4)
Size: 12
Dimensions: 2

Array 5:
Data Type: int64
Shape: (3, 4)
Size: 12
Dimensions: 2



In [42]:
#question-5
random_float_array1=np.random.rand(3,4)
print('Float Array-1:-')
print(random_float_array1)
random_float_array2=np.random.uniform(1,10,size=(3,4))
print('Float Array-1:-')
print(random_float_array2)

Float Array-1:-
[[0.32278013 0.0567663  0.63494655 0.8070406 ]
 [0.39760876 0.2935663  0.68972468 0.3561905 ]
 [0.82165535 0.69517153 0.04227614 0.36730134]]
Float Array-1:-
[[1.33150755 5.50863438 4.38395155 1.00276855]
 [3.04428834 1.91392466 9.47291971 2.16665195]
 [6.45809765 3.6541205  9.78502391 2.17859457]]


In [46]:
#question-6
from scipy import stats
array=np.random.rand(10)
print(array)
mean=np.mean(array)
print('\nmean:-',mean)
mode=stats.mode(array)
print('\nmode:-',mode)
median=np.median(array)
print('\nmedian:-',median)
variance=np.var(array)
print('\nvariance:-',variance)
standard_deviation=np.std(array)
print('\nstandard deviation:-',standard_deviation)

[0.70839739 0.16849408 0.61889742 0.80263392 0.05020844 0.37649271
 0.8180667  0.54572285 0.30440295 0.72723944]

mean:- 0.5120555893615821

mode:- ModeResult(mode=0.05020843690764487, count=1)

median:- 0.5823101364279413

variance:- 0.06683156355942407

standard deviation:- 0.25851801399404273


In [47]:
#question-7
array_x = np.random.rand(10)
array_y = np.random.rand(10)

correlation_coefficient = np.corrcoef(array_x, array_y)[0, 1]
print("\nCorrelation Coefficient:", correlation_coefficient)


Correlation Coefficient: 0.1933559656822542
